title:            win.moe
description:      每天进步一点点.
url:              win.moe
signoff:          每天进步一点点.

#facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
#google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Home
    url:          /
  - name:         关于
    url:          /about
  - name:         豆瓣
    url:          /douban
  - name:         LOFTER
    url:          http://3.1415926.info
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
